### PR TITLE
Open debugging port to the core

### PR DESCRIPTION
**Pull request by tokland**
https://app.clickup.com/t/86941z0ab

#86941z0ab

- Automatically open and expose --debug-port=PORT for debugging with a Java IDE (IDEA, for example)

```shell
$ git clone https://github.com/dhis2/dhis2-core
$ git checkout v2.37.10 # version to debug, it should match the WAR version
```

### CODE REVIEW

**Comment by 9sneha-n** [comment]
As discussed with Arnau, I am unable to debug due to an issue specific to MAC M1 machine. I will try to debug further at a later time, but do not want to block the merging of this PR.

**Review by 9sneha-n — APPROVED** [review]

**Comment by anagperal** [comment]
Tested with data `docker.eyeseetea.com/eyeseetea/dhis2-data:2.37.9-sierra `and `docker.eyeseetea.com/eyeseetea/dhis2-data:2.37.10-test` both with core options `--core-image=docker.eyeseetea.com/eyeseetea/dhis2-core:2.37.10 --debug-port=7080`. All the docker part is correct, but when I configure the debugger in IntelliJ I get the following error: 
Screenshot from 2024-03-22 13-43-57
Tested in Ubuntu 22.04.3 LTS

**Comment by tokland** [comment]
I see what's happening. Depending on the JDK version, the debug port listens to all or only localhost, that's why it was core-dependent. ea876a07: Now it's forcing a binding to `0.0.0.0` so it should work for any core. 

Can you test again? @9sneha-n @anagperal

**Comment by 9sneha-n** [comment]
> I see what's happening. Depending on the JDK version, the debug port listens to all or only localhost, that's why it was core-dependent. [ea876a0](https://github.com/EyeSeeTea/d2-docker/commit/ea876a07b2ceced0279493c6c0069214d00a1c2b): Now it's forcing a binding to `0.0.0.0` so it should work for any core.
> 
> Can you test again? @9sneha-n @anagperal

I am still getting the same error :( 
Screenshot 2024-03-25 at 1 36 37 PM

**Comment by anagperal** [comment]
> I see what's happening. Depending on the JDK version, the debug port listens to all or only localhost, that's why it was core-dependent. [ea876a0](https://github.com/EyeSeeTea/d2-docker/commit/ea876a07b2ceced0279493c6c0069214d00a1c2b): Now it's forcing a binding to `0.0.0.0` so it should work for any core.
> 
> Can you test again? @9sneha-n @anagperal

Hi! For me, it's already working. Thanks! 
Screenshot from 2024-03-25 09-38-47

**Comment by tokland** [comment]
> For me, it's already working

Cool! So maybe Sneha is still stuck with the Mac-specific problem. We'll check it out, anyway.

**Comment by 9sneha-n** [comment]
> > For me, it's already working
> 
> Cool! So maybe Sneha is still stuck with the Mac-specific problem. We'll check it out, anyway.

The debug port works for me too! thank you @tokland for taking time to figure out the issue :D

**Comment by tokland** [comment]
@eperedo Can you test the current version in Windows?

**Comment by eperedo** [comment]
@tokland Sorry, I didn't have time to test it again. I'll try to do it as soon as possible.

**Comment by tokland** [comment]
- [ ] To avoid exposing random debug port if not specified -> refactor: generate dynamic yaml + use to remove debug-port reference if empty

**Pull request merged**
