### PR TITLE
Release 1.5.0

### PR DESCRIPTION
**Pull request by adrianq**

### CODE REVIEW

**Review by ifoche — APPROVED** [review]
Thanks! It looks fine for me. I've tested it with a normal 2.36 WIDP copy and it seems to be working properly. The other reviewers (@adrianq , @tokland ) do you validate this release?

**Comment by adrianq** [comment]
Yep, I am fine with this release. Actually, most of this feature are already in use in the SP servers. Thanks!

**Comment by ifoche** [comment]
ok, then... I'm merging it assuming that it implies tokland having reviewed it already. BTW, the only little modification I've made is to increase the version number so it matches the PR name... which was probably expected already. But as you say it is in use in SP servers, if you want to update it after it gets merged, maybe that will avoid you thinking you're still in 1.4 in the future :)

**Comment by tokland** [comment]
:+1: We've been using the development branch for some time on Samaritans instances, all good.

**Pull request merged**
